# Default values for cert-manager-issuers.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

letsencrypt_email: "livekit-demo@letsencrypt.cloudportal.app"
domain: "livekit-demo.cloudportal.app"
tenant: "master"
