# LiveKit Ingress configuration
replicaCount: 2

# LiveKit Ingress server configuration
ingress:
  api_key: test
  api_secret: Test123123
  ws_url: wss://livekit.livekit-demo.cloudportal.app
  redis:
    address: redis-redis-cluster.redis.svc.cluster.local:6379
    db: 0
  # Keep other default values
  logging:
    level: info
  health_port: 7888
  prometheus_port: 7889
  http_relay_port: 9090
  rtmp_port: 1935
  whip_port: 8080
  rtc_config:
    use_external_ip: true
    udp_port: 7885
  cpu_cost:
    rtmp_cpu_cost: 2
    whip_cpu_cost: 2
    whip_bypass_transcoding_cpu_cost: 0.1

# Note: This helm chart doesn't support Kubernetes Ingress resources
# The service is exposed via LoadBalancer type service on ports 1935 (RTMP), 7888 (HTTP), 8080 (WHIP)

# Autoscaling configuration
autoscaling:
  enabled: true
  minReplicas: 2
  maxReplicas: 10
  targetCPUUtilizationPercentage: 70

# Resource allocation
resources:
  requests:
    cpu: 500m
    memory: 1Gi
  limits:
    cpu: 2000m
    memory: 4Gi

# Service configuration for RTMP ingestion
service:
  rtmp:
    enabled: true
    type: LoadBalancer
    port: 1935
    annotations:
      # Add any cloud provider specific annotations here if needed

# Pod configuration
podAnnotations:
  prometheus.io/scrape: "true"
  prometheus.io/port: "7888"
  prometheus.io/path: "/metrics"

# Service monitor for Prometheus
serviceMonitor:
  enabled: true