---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: operator-ca
  namespace: minio-operator
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  secretName: operator-ca-tls
  isCA: true
  commonName: minio-operator-ca
  dnsNames:
    - minio-operator-ca
  duration: 87600h # 10 years
  renewBefore: 8760h # 1 year
  issuerRef:
    name: selfsigned-issuer
    kind: Issuer
---
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: selfsigned-issuer
  namespace: minio-operator
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  selfSigned: {}