apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd-metrics
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "5"
spec:
  project: core-services
  source:
    repoURL: https://github.com/QumulusTechnology/livekit-demo.git
    targetRevision: main
    path: services/argocd-metrics/manifests
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
      allowEmpty: true
    syncOptions:
      - CreateNamespace=true