apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: harbor
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  project: core-services
  sources:
    - repoURL: https://github.com/QumulusTechnology/livekit-demo.git
      targetRevision: main
      ref: vals

    - repoURL: https://helm.goharbor.io
      chart: harbor
      targetRevision: 1.15.1
      helm:
        valueFiles:
          - $vals/services/harbor/values.yaml

  destination:
    server: https://kubernetes.default.svc
    namespace: harbor
  syncPolicy:
    automated:
      selfHeal: true
      allowEmpty: true
    syncOptions:
      - CreateNamespace=true
