apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ingress-nginx
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  project: core-services

  source:
    repoURL: https://kubernetes.github.io/ingress-nginx
    targetRevision: 4.12.3
    chart: ingress-nginx
    helm:
      values: |
        installCRDs: 'true'
        fullnameOverride: 'ingress-nginx'
        controller:
          admissionWebhooks:
            enabled: false
        service:
          annotations:
            service.beta.kubernetes.io/openstack-internal-load-balancer: 'true'
          externalTrafficPolicy: 'Local'

  destination:
    server: https://kubernetes.default.svc
    namespace: ingress-nginx
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
      - CreateNamespace=true
