apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: livekit-manifests
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "3"
spec:
  project: core-services
  destination:
    server: https://kubernetes.default.svc
    namespace: livekit
  sources:
    - repoURL: https://github.com/QumulusTechnology/livekit-demo.git
      targetRevision: main
      path: services/livekit/manifests
      helm:
        valueFiles:
          - values.yaml
  syncPolicy:
    automated:
      prune: false
      selfHeal: true
      allowEmpty: true
    syncOptions:
      - CreateNamespace=true