apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: livekit
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  project: core-services
  sources:
    - repoURL: https://github.com/QumulusTechnology/livekit-demo.git
      targetRevision: main
      ref: vals

    - repoURL: https://helm.livekit.io
      targetRevision: 1.9.0
      chart: livekit-server
      helm:
        valueFiles:
          - $vals/services/livekit/values.yaml

  destination:
    server: https://kubernetes.default.svc
    namespace: livekit
  syncPolicy:
    automated:
      selfHeal: true
      prune: false
      allowEmpty: true
    syncOptions:
      - CreateNamespace=true
