apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prometheus-crd
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  project: core-services
  sources:
    - repoURL: https://prometheus-community.github.io/helm-charts
      targetRevision: 21.0.0
      chart: prometheus-operator-crds
  destination:
    server: https://kubernetes.default.svc
    namespace: grafana-agent
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
      allowEmpty: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
