apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: trivoh
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "4"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/QumulusTechnology/livekit-demo.git
    targetRevision: main
    path: services/trivoh/manifests
    helm:
      valueFiles:
        - ../values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: trivoh
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true