apiVersion: v1
kind: ConfigMap
metadata:
  name: trivoh-db-init-script
  namespace: {{ .Release.Namespace }}
  annotations:
    argocd.argoproj.io/sync-wave: "0"
data:
  init.sql: |
    SET FOREIGN_KEY_CHECKS = 0;
    SET sql_mode = '';
    
    -- Create all tables without foreign key constraints first
    CREATE TABLE IF NOT EXISTS users (
      id VARCHAR(55) NOT NULL, 
      name VARCHAR(255), 
      email VARCHAR(255) UNIQUE, 
      avatar VARCHAR(255), 
      timezone VARCHAR(255), 
      online_status VARCHAR(255), 
      created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, 
      updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP, 
      PRIMARY KEY (id)
    ) ENGINE=InnoDB;
    
    CREATE TABLE IF NOT EXISTS projects (
      id INTEGER NOT NULL AUTO_INCREMENT, 
      name VARCHAR(255), 
      description TEXT, 
      created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, 
      updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP, 
      PRIMARY KEY (id)
    ) ENGINE=InnoDB;
    
    CREATE TABLE IF NOT EXISTS project_tasks (
      id INTEGER NOT NULL AUTO_INCREMENT, 
      project_id INTEGER, 
      title VARCHAR(255), 
      description TEXT, 
      status VARCHAR(255), 
      created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, 
      updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP, 
      PRIMARY KEY (id)
    ) ENGINE=InnoDB;
    
    CREATE TABLE IF NOT EXISTS project_task_links (
      id INTEGER AUTO_INCREMENT, 
      task_id INTEGER NOT NULL, 
      title VARCHAR(255) NOT NULL, 
      link VARCHAR(255) NOT NULL, 
      icon VARCHAR(255), 
      created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, 
      updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP, 
      PRIMARY KEY (id)
    ) ENGINE=InnoDB;
    
    CREATE TABLE IF NOT EXISTS project_task_time_trackings (
      id INTEGER AUTO_INCREMENT, 
      task_id INTEGER NOT NULL, 
      user_id INTEGER NOT NULL, 
      start_time DATETIME DEFAULT CURRENT_TIMESTAMP, 
      hours INTEGER NOT NULL DEFAULT 0, 
      minutes INTEGER NOT NULL DEFAULT 0, 
      estimated_hours INTEGER NOT NULL DEFAULT 0, 
      estimated_minutes INTEGER NOT NULL DEFAULT 0, 
      created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, 
      updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP, 
      PRIMARY KEY (id)
    ) ENGINE=InnoDB;
    
    CREATE TABLE IF NOT EXISTS meetings (
      id INTEGER NOT NULL AUTO_INCREMENT, 
      uuid VARCHAR(255), 
      title VARCHAR(255), 
      category VARCHAR(255), 
      user_id VARCHAR(55), 
      schedule VARCHAR(255), 
      invitatin_emails TEXT, 
      schedule_date DATETIME, 
      start_time VARCHAR(255), 
      end_time VARCHAR(255), 
      ip VARCHAR(255), 
      slug VARCHAR(255), 
      views INTEGER DEFAULT 0, 
      image VARCHAR(255), 
      status VARCHAR(255), 
      server_id VARCHAR(255), 
      password VARCHAR(255), 
      meeting_password VARCHAR(255), 
      camera_allowed BOOLEAN DEFAULT TRUE, 
      microphone_allowed BOOLEAN DEFAULT TRUE, 
      screen_sharing BOOLEAN DEFAULT TRUE, 
      lobby_enabled BOOLEAN DEFAULT FALSE, 
      host_enabled BOOLEAN DEFAULT TRUE, 
      guest_allowed BOOLEAN DEFAULT TRUE, 
      timezone VARCHAR(255), 
      reminded INTEGER DEFAULT 0, 
      sequence INTEGER, 
      end_date DATETIME, 
      created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, 
      updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP, 
      PRIMARY KEY (id)
    ) ENGINE=InnoDB;
    
    CREATE TABLE IF NOT EXISTS documents_data (
      id INTEGER NOT NULL AUTO_INCREMENT,
      slug VARCHAR(255),
      content TEXT,
      created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
      updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
      PRIMARY KEY (id)
    ) ENGINE=InnoDB;
    
    -- Add more tables as needed
    
    SET FOREIGN_KEY_CHECKS = 1;