apiVersion: v1
kind: Secret
metadata:
  name: harbor-regcred
  namespace: {{ .Release.Namespace }}
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ printf "{\"auths\":{\"repo.livekit-demo.cloudportal.app\":{\"username\":\"admin\",\"password\":\"%s\",\"auth\":\"%s\"}}}" (required "Harbor password required" .Values.harbor.password) (printf "admin:%s" (required "Harbor password required" .Values.harbor.password) | b64enc) | b64enc }}