{{- if .Values.ingress.enabled -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "trivoh-api.fullname" . }}
  labels:
    {{- include "trivoh-api.labels" . | nindent 4 }}
  {{- with .Values.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- if .Values.ingress.className }}
  ingressClassName: {{ .Values.ingress.className }}
  {{- end }}
  {{- if .Values.ingress.tls }}
  tls:
    - hosts:
        - api.{{ .Values.domain }}
      secretName: trivoh-api-tls
  {{- end }}
  rules:
    - host: api.{{ .Values.domain }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ include "trivoh-api.fullname" . }}
                port:
                  number: {{ .Values.service.port }}
{{- end }}