apiVersion: generators.external-secrets.io/v1alpha1
kind: Password
metadata:
  name: mysql-root-password
  namespace: {{ .Release.Namespace }}
  annotations:
    argocd.argoproj.io/sync-wave: "-2"
spec:
  length: 32
  digits: 10
  symbols: 6
  noUpper: false
  allowRepeat: true
---
apiVersion: generators.external-secrets.io/v1alpha1
kind: Password
metadata:
  name: mysql-user-password
  namespace: {{ .Release.Namespace }}
  annotations:
    argocd.argoproj.io/sync-wave: "-2"
spec:
  length: 24
  digits: 8
  symbols: 4
  noUpper: false
  allowRepeat: true
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: mysql-credentials
  namespace: {{ .Release.Namespace }}
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
    argocd.argoproj.io/sync-wave: "-1"
spec:
  refreshInterval: "0"
  target:
    name: mysql-credentials
    creationPolicy: Owner
    deletionPolicy: Retain
    template:
      data:
        root-password: "{{ `{{ .rootPassword }}` }}"
        password: "{{ `{{ .userPassword }}` }}"
        user: "trivoh_user"
        database: "trivoh"
      engineVersion: v2
      mergePolicy: Replace
  data:
  - secretKey: rootPassword
    sourceRef:
      generatorRef:
        apiVersion: generators.external-secrets.io/v1alpha1
        kind: Password
        name: mysql-root-password
    remoteRef:
      property: password
  - secretKey: userPassword
    sourceRef:
      generatorRef:
        apiVersion: generators.external-secrets.io/v1alpha1
        kind: Password
        name: mysql-user-password
    remoteRef:
      property: password