apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "trivoh-api.fullname" . }}-metrics
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "trivoh-api.labels" . | nindent 4 }}
    app.kubernetes.io/component: metrics
spec:
  selector:
    matchLabels:
      {{- include "trivoh-api.selectorLabels" . | nindent 6 }}
  endpoints:
  - port: http
    interval: 30s
    path: /metrics
    scrapeTimeout: 10s
  - port: http
    interval: 30s
    path: /health/metrics
    scrapeTimeout: 10s
  namespaceSelector:
    matchNames:
    - {{ .Release.Namespace }}