apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "meet-client.fullname" . }}
  labels:
    {{- include "meet-client.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "meet-client.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "meet-client.selectorLabels" . | nindent 8 }}
    spec:
      imagePullSecrets:
        - name: harbor-registry
      containers:
        - name: {{ .Chart.Name }}
          image: "repo.{{ .Values.domain }}/{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: 30
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: 5
            periodSeconds: 5
          env:
            - name: LIVEKIT_URL
              value: "wss://livekit.{{ .Values.domain }}"
            - name: TRIVOH_API_URL
              value: "https://api.{{ .Values.domain }}"
            {{- range .Values.env }}
            {{- if and (ne .name "LIVEKIT_URL") (ne .name "TRIVOH_API_URL") }}
            - name: {{ .name }}
              {{- if .value }}
              value: {{ .value | quote }}
              {{- else if .valueFrom }}
              valueFrom:
                {{- toYaml .valueFrom | nindent 16 }}
              {{- end }}
            {{- end }}
            {{- end }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}