apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: harbor-registry
  namespace: {{ .Release.Namespace }}
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: harbor-registry-secrets
    kind: ClusterSecretStore
  target:
    name: harbor-registry
    template:
      type: kubernetes.io/dockerconfigjson
  data:
  - secretKey: .dockerconfigjson
    remoteRef:
      key: harbor-docker-registry
      property: .dockerconfigjson