{{- if .Values.ingress.enabled -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "meet-client.fullname" . }}
  labels:
    {{- include "meet-client.labels" . | nindent 4 }}
  {{- with .Values.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- if .Values.ingress.className }}
  ingressClassName: {{ .Values.ingress.className }}
  {{- end }}
  {{- if .Values.ingress.tls }}
  tls:
    - hosts:
        - meet.{{ .Values.domain }}
      secretName: meet-client-tls
  {{- end }}
  rules:
    - host: meet.{{ .Values.domain }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ include "meet-client.fullname" . }}
                port:
                  number: {{ .Values.service.port }}
{{- end }}