apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: livekit-keys-file
  namespace: {{ .Release.Namespace }}
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: livekit-secrets-store
    kind: ClusterSecretStore
  target:
    name: livekit-keys-file
  dataFrom:
  - extract:
      key: livekit-keys-file