#cloud-config
hostname: ${vm_name}
manage_etc_hosts: true

package_update: true
package_upgrade: true

packages:
  - curl
  - wget
  - htop
  - iotop
  - sysstat
  - net-tools
  - jq
  - bc
  - python3-pip
  - ansible

# Optimize system for load testing
write_files:
  - path: /etc/sysctl.d/99-load-test.conf
    content: |
      # Network optimizations for load testing
      net.core.rmem_max = 134217728
      net.core.wmem_max = 134217728
      net.ipv4.tcp_rmem = 4096 87380 134217728
      net.ipv4.tcp_wmem = 4096 65536 134217728
      net.core.netdev_max_backlog = 5000
      net.ipv4.tcp_congestion_control = bbr
      net.core.default_qdisc = fq
      
      # Connection tracking
      net.netfilter.nf_conntrack_max = 524288
      net.nf_conntrack_max = 524288
      
      # File descriptors
      fs.file-max = 2097152
      fs.nr_open = 2097152

  - path: /etc/security/limits.d/99-load-test.conf
    content: |
      * soft nofile 1048576
      * hard nofile 1048576
      * soft nproc 65536
      * hard nproc 65536

runcmd:
  # Apply sysctl settings
  - sysctl -p /etc/sysctl.d/99-load-test.conf
  
  # Install LiveKit CLI
  - curl -sSL https://get.livekit.io/cli | bash
  - mv /usr/local/bin/lk /usr/local/bin/lk || true
  
  # Create directories
  - mkdir -p /home/ubuntu/load-test/{logs,results}
  - chown -R ubuntu:ubuntu /home/ubuntu/load-test
  
  # Signal completion
  - echo "VM ${vm_index} initialization complete" > /home/ubuntu/init-complete.flag