apiVersion: generators.external-secrets.io/v1alpha1
kind: Password
metadata:
  name: livekit-api-secret
  namespace: {{ .Release.Namespace }}
  annotations:
    argocd.argoproj.io/sync-wave: "-2"
spec:
  length: 32
  digits: 10
  symbols: 6
  noUpper: false
  allowRepeat: true
---
apiVersion: generators.external-secrets.io/v1alpha1
kind: Password
metadata:
  name: minio-access-key
  namespace: {{ .Release.Namespace }}
  annotations:
    argocd.argoproj.io/sync-wave: "-2"
spec:
  length: 20
  digits: 6
  symbols: 0
  noUpper: true
  allowRepeat: false
---
apiVersion: generators.external-secrets.io/v1alpha1
kind: Password
metadata:
  name: minio-secret-key
  namespace: {{ .Release.Namespace }}
  annotations:
    argocd.argoproj.io/sync-wave: "-2"
spec:
  length: 40
  digits: 12
  symbols: 8
  noUpper: false
  allowRepeat: true
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: livekit-credentials
  namespace: {{ .Release.Namespace }}
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
    argocd.argoproj.io/sync-wave: "-1"
spec:
  refreshInterval: "0"
  target:
    name: livekit-credentials
    creationPolicy: Owner
    deletionPolicy: Retain
    template:
      data:
        api-key: "livekit"
        api-secret: "{{ `{{ .livekitSecret }}` }}"
        LIVEKIT_KEYS: "livekit:{{ `{{ .livekitSecret }}` }}"
      engineVersion: v2
      mergePolicy: Replace
  dataFrom:
  - sourceRef:
      generatorRef:
        apiVersion: generators.external-secrets.io/v1alpha1
        kind: Password
        name: livekit-api-secret
    rewrite:
    - regexp:
        source: "password"
        target: "livekitSecret"
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: minio-credentials
  namespace: {{ .Release.Namespace }}
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
    argocd.argoproj.io/sync-wave: "-1"
spec:
  refreshInterval: "0"
  target:
    name: minio-credentials
    creationPolicy: Owner
    deletionPolicy: Retain
    template:
      data:
        access-key: "{{ `{{ .accessKey }}` }}"
        secret-key: "{{ `{{ .secretKey }}` }}"
        LIVEKIT_S3_ACCESS_KEY: "{{ `{{ .accessKey }}` }}"
        LIVEKIT_S3_SECRET: "{{ `{{ .secretKey }}` }}"
        S3_ACCESS_KEY: "{{ `{{ .accessKey }}` }}"
        S3_SECRET_KEY: "{{ `{{ .secretKey }}` }}"
      engineVersion: v2
      mergePolicy: Replace
  data:
  - secretKey: accessKey
    sourceRef:
      generatorRef:
        apiVersion: generators.external-secrets.io/v1alpha1
        kind: Password
        name: minio-access-key
    remoteRef:
      property: password
  - secretKey: secretKey
    sourceRef:
      generatorRef:
        apiVersion: generators.external-secrets.io/v1alpha1
        kind: Password
        name: minio-secret-key
    remoteRef:
      property: password