apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: k8s-rules
  labels:
    app: grafana-agent
    tenant: {{ .Values.tenant }}
spec:
  groups:
    - name: k8s.rules
      rules:
        - record: node_namespace_pod_container:container_cpu_usage_seconds_total:sum_irate
          expr: |-
            sum by (cluster, namespace, pod, container) (irate(container_cpu_usage_seconds_total{image!="",job="integrations/kubernetes/cadvisor"}[5m])) * on (cluster, namespace, pod) group_left (node) topk by (cluster, namespace, pod) (1, max by (cluster, namespace, pod, node) (kube_pod_info{node!=""}))
        - record: node_namespace_pod_container:container_memory_working_set_bytes
          expr: |-
            container_memory_working_set_bytes{image!="",job="integrations/kubernetes/cadvisor"} * on (cluster, namespace, pod) group_left (node) topk by (cluster, namespace, pod) (1, max by (cluster, namespace, pod, node) (kube_pod_info{node!=""}))
        - record: node_namespace_pod_container:container_memory_rss
          expr: |-
            container_memory_rss{image!="",job="integrations/kubernetes/cadvisor"} * on (cluster, namespace, pod) group_left (node) topk by (cluster, namespace, pod) (1, max by (cluster, namespace, pod, node) (kube_pod_info{node!=""}))
        - record: node_namespace_pod_container:container_memory_cache
          expr: |-
            container_memory_cache{image!="",job="integrations/kubernetes/cadvisor"} * on (cluster, namespace, pod) group_left (node) topk by (cluster, namespace, pod) (1, max by (cluster, namespace, pod, node) (kube_pod_info{node!=""}))
        - record: node_namespace_pod_container:container_memory_swap
          expr: |-
            container_memory_swap{image!="",job="integrations/kubernetes/cadvisor"} * on (cluster, namespace, pod) group_left (node) topk by (cluster, namespace, pod) (1, max by (cluster, namespace, pod, node) (kube_pod_info{node!=""}))
        - record: cluster:namespace:pod_memory:active:kube_pod_container_resource_requests
          expr: |-
            kube_pod_container_resource_requests{job="integrations/kubernetes/kube-state-metrics",resource="memory"} * on (namespace, pod, cluster) group_left () max by (namespace, pod, cluster) ((kube_pod_status_phase{phase=~"Pending|Running"} == 1))
        - record: namespace_memory:kube_pod_container_resource_requests:sum
          expr: |-
            sum by (namespace, cluster) (sum by (namespace, pod, cluster) (max by (namespace, pod, container, cluster) (kube_pod_container_resource_requests{job="integrations/kubernetes/kube-state-metrics",resource="memory"}) * on (namespace, pod, cluster) group_left () max by (namespace, pod, cluster) (kube_pod_status_phase{phase=~"Pending|Running"} == 1)))
        - record: cluster:namespace:pod_cpu:active:kube_pod_container_resource_requests
          expr: |-
            kube_pod_container_resource_requests{job="integrations/kubernetes/kube-state-metrics",resource="cpu"} * on (namespace, pod, cluster) group_left () max by (namespace, pod, cluster) ((kube_pod_status_phase{phase=~"Pending|Running"} == 1))
        - record: namespace_cpu:kube_pod_container_resource_requests:sum
          expr: |-
            sum by (namespace, cluster) (sum by (namespace, pod, cluster) (max by (namespace, pod, container, cluster) (kube_pod_container_resource_requests{job="integrations/kubernetes/kube-state-metrics",resource="cpu"}) * on (namespace, pod, cluster) group_left () max by (namespace, pod, cluster) (kube_pod_status_phase{phase=~"Pending|Running"} == 1)))
        - record: cluster:namespace:pod_memory:active:kube_pod_container_resource_limits
          expr: |-
            kube_pod_container_resource_limits{job="integrations/kubernetes/kube-state-metrics",resource="memory"} * on (namespace, pod, cluster) group_left () max by (namespace, pod, cluster) ((kube_pod_status_phase{phase=~"Pending|Running"} == 1))
        - record: namespace_memory:kube_pod_container_resource_limits:sum
          expr: |-
            sum by (namespace, cluster) (sum by (namespace, pod, cluster) (max by (namespace, pod, container, cluster) (kube_pod_container_resource_limits{job="integrations/kubernetes/kube-state-metrics",resource="memory"}) * on (namespace, pod, cluster) group_left () max by (namespace, pod, cluster) (kube_pod_status_phase{phase=~"Pending|Running"} == 1)))
        - record: cluster:namespace:pod_cpu:active:kube_pod_container_resource_limits
          expr: |-
            kube_pod_container_resource_limits{job="integrations/kubernetes/kube-state-metrics",resource="cpu"} * on (namespace, pod, cluster) group_left () max by (namespace, pod, cluster) ((kube_pod_status_phase{phase=~"Pending|Running"} == 1))
        - record: namespace_cpu:kube_pod_container_resource_limits:sum
          expr: |-
            sum by (namespace, cluster) (sum by (namespace, pod, cluster) (max by (namespace, pod, container, cluster) (kube_pod_container_resource_limits{job="integrations/kubernetes/kube-state-metrics",resource="cpu"}) * on (namespace, pod, cluster) group_left () max by (namespace, pod, cluster) (kube_pod_status_phase{phase=~"Pending|Running"} == 1)))
        - record: namespace_workload_pod:kube_pod_owner:relabel
          expr: |-
            max by (cluster, namespace, workload, pod) (label_replace(label_replace(kube_pod_owner{job="integrations/kubernetes/kube-state-metrics",owner_kind="ReplicaSet"}, "replicaset", "$1", "owner_name", "(.*)") * on (replicaset, namespace, cluster) group_left (owner_name) topk by (replicaset, namespace, cluster) (1, max by (replicaset, namespace, owner_name, cluster) (kube_replicaset_owner{job="integrations/kubernetes/kube-state-metrics"})), "workload", "$1", "owner_name", "(.*)"))
          labels:
            workload_type: deployment
        - record: namespace_workload_pod:kube_pod_owner:relabel
          expr: |-
            max by (cluster, namespace, workload, pod) (label_replace(kube_pod_owner{job="integrations/kubernetes/kube-state-metrics",owner_kind="DaemonSet"}, "workload", "$1", "owner_name", "(.*)"))
          labels:
            workload_type: daemonset
        - record: namespace_workload_pod:kube_pod_owner:relabel
          expr: |-
            max by (cluster, namespace, workload, pod) (label_replace(kube_pod_owner{job="integrations/kubernetes/kube-state-metrics",owner_kind="StatefulSet"}, "workload", "$1", "owner_name", "(.*)"))
          labels:
            workload_type: statefulset
        - record: namespace_workload_pod:kube_pod_owner:relabel
          expr: |-
            max by (cluster, namespace, workload, pod) (label_replace(kube_pod_owner{job="integrations/kubernetes/kube-state-metrics",owner_kind="Job"}, "workload", "$1", "owner_name", "(.*)"))
          labels:
            workload_type: job
