apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: kube-prometheus-node-recording-rules
  labels:
    app: grafana-agent
    tenant: {{ .Values.tenant }}
spec:
  groups:
    - name: kube-prometheus-node-recording.rules
      rules:
        - record: instance:node_cpu:rate:sum
          expr: sum by (instance, cluster) (rate(node_cpu_seconds_total{mode!="idle",mode!="iowait",mode!="steal"}[3m]))
        - record: instance:node_network_receive_bytes:rate:sum
          expr: sum by (instance, cluster) (rate(node_network_receive_bytes_total[3m]))
        - record: instance:node_network_transmit_bytes:rate:sum
          expr: sum by (instance, cluster) (rate(node_network_transmit_bytes_total[3m]))
        - record: instance:node_cpu:ratio
          expr: sum without (cpu, mode) (rate(node_cpu_seconds_total{mode!="idle",mode!="iowait",mode!="steal"}[5m])) / on (instance, cluster) group_left () count by (instance, cluster) (sum by (instance, cpu, cluster) (node_cpu_seconds_total))
        - record: cluster:node_cpu:sum_rate5m
          expr: sum by (cluster) (rate(node_cpu_seconds_total{mode!="idle",mode!="iowait",mode!="steal"}[5m]))
        - record: cluster:node_cpu:ratio
          expr: cluster:node_cpu:sum_rate5m / count by (cluster) (sum by (instance, cpu, cluster) (node_cpu_seconds_total))
