apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: kube-apiserver-availability-rules
  labels:
    app: grafana-agent
    tenant: {{ .Values.tenant }}
spec: 
  groups:
    - name: kube-apiserver-availability.rules
      interval: 3m
      rules:
        - record: code_verb:apiserver_request_total:increase30d
          expr: avg_over_time(code_verb:apiserver_request_total:increase1h[30d]) * 24 * 30
        - record: code:apiserver_request_total:increase30d
          expr: sum by (cluster, code) (code_verb:apiserver_request_total:increase30d{verb=~"LIST|GET"})
          labels:
            verb: read
        - record: code:apiserver_request_total:increase30d
          expr: sum by (cluster, code) (code_verb:apiserver_request_total:increase30d{verb=~"POST|PUT|PATCH|DELETE"})
          labels:
            verb: write
        - record: cluster_verb_scope:apiserver_request_slo_duration_seconds_count:increase1h
          expr: sum by (cluster, verb, scope) (increase(apiserver_request_slo_duration_seconds_count[1h]))
        - record: cluster_verb_scope:apiserver_request_slo_duration_seconds_count:increase30d
          expr: sum by (cluster, verb, scope) (avg_over_time(cluster_verb_scope:apiserver_request_slo_duration_seconds_count:increase1h[30d]) * 24 * 30)
        - record: cluster_verb_scope_le:apiserver_request_slo_duration_seconds_bucket:increase1h
          expr: sum by (cluster, verb, scope, le) (increase(apiserver_request_slo_duration_seconds_bucket[1h]))
        - record: cluster_verb_scope_le:apiserver_request_slo_duration_seconds_bucket:increase30d
          expr: sum by (cluster, verb, scope, le) (avg_over_time(cluster_verb_scope_le:apiserver_request_slo_duration_seconds_bucket:increase1h[30d]) * 24 * 30)
        - record: apiserver_request:availability30d
          expr: |-
            1 - ((sum by (cluster) (cluster_verb_scope:apiserver_request_slo_duration_seconds_count:increase30d{verb=~"POST|PUT|PATCH|DELETE"}) - sum by (cluster) (cluster_verb_scope_le:apiserver_request_slo_duration_seconds_bucket:increase30d{le="1",verb=~"POST|PUT|PATCH|DELETE"})) + (sum by (cluster) (cluster_verb_scope:apiserver_request_slo_duration_seconds_count:increase30d{verb=~"LIST|GET"}) - ((sum by (cluster) (cluster_verb_scope_le:apiserver_request_slo_duration_seconds_bucket:increase30d{le="1",scope=~"resource|",verb=~"LIST|GET"}) or vector(0)) + sum by (cluster) (cluster_verb_scope_le:apiserver_request_slo_duration_seconds_bucket:increase30d{le="5",scope="namespace",verb=~"LIST|GET"}) + sum by (cluster) (cluster_verb_scope_le:apiserver_request_slo_duration_seconds_bucket:increase30d{le="30",scope="cluster",verb=~"LIST|GET"}))) + sum by (cluster) (code:apiserver_request_total:increase30d{code=~"5.."} or vector(0))) / sum by (cluster) (code:apiserver_request_total:increase30d)
          labels:
            verb: all
        - record: apiserver_request:availability30d
          expr: |-
            1 - (sum by (cluster) (cluster_verb_scope:apiserver_request_slo_duration_seconds_count:increase30d{verb=~"LIST|GET"}) - ((sum by (cluster) (cluster_verb_scope_le:apiserver_request_slo_duration_seconds_bucket:increase30d{le="1",scope=~"resource|",verb=~"LIST|GET"}) or vector(0)) + sum by (cluster) (cluster_verb_scope_le:apiserver_request_slo_duration_seconds_bucket:increase30d{le="5",scope="namespace",verb=~"LIST|GET"}) + sum by (cluster) (cluster_verb_scope_le:apiserver_request_slo_duration_seconds_bucket:increase30d{le="30",scope="cluster",verb=~"LIST|GET"})) + sum by (cluster) (code:apiserver_request_total:increase30d{code=~"5..",verb="read"} or vector(0))) / sum by (cluster) (code:apiserver_request_total:increase30d{verb="read"})
          labels:
            verb: read
        - record: apiserver_request:availability30d
          expr: |-
            1 - ((sum by (cluster) (cluster_verb_scope:apiserver_request_slo_duration_seconds_count:increase30d{verb=~"POST|PUT|PATCH|DELETE"}) - sum by (cluster) (cluster_verb_scope_le:apiserver_request_slo_duration_seconds_bucket:increase30d{le="1",verb=~"POST|PUT|PATCH|DELETE"})) + sum by (cluster) (code:apiserver_request_total:increase30d{code=~"5..",verb="write"} or vector(0))) / sum by (cluster) (code:apiserver_request_total:increase30d{verb="write"})
          labels:
            verb: write
        - record: code_resource:apiserver_request_total:rate5m
          expr: sum by (cluster, code, resource) (rate(apiserver_request_total{job="apiserver",verb=~"LIST|GET"}[5m]))
          labels:
            verb: read
        - record: code_resource:apiserver_request_total:rate5m
          expr: sum by (cluster, code, resource) (rate(apiserver_request_total{job="apiserver",verb=~"POST|PUT|PATCH|DELETE"}[5m]))
          labels:
            verb: write
        - record: code_verb:apiserver_request_total:increase1h
          expr: sum by (cluster, code, verb) (increase(apiserver_request_total{code=~"2..",job="apiserver",verb=~"LIST|GET|POST|PUT|PATCH|DELETE"}[1h]))
        - record: code_verb:apiserver_request_total:increase1h
          expr: sum by (cluster, code, verb) (increase(apiserver_request_total{code=~"3..",job="apiserver",verb=~"LIST|GET|POST|PUT|PATCH|DELETE"}[1h]))
        - record: code_verb:apiserver_request_total:increase1h
          expr: sum by (cluster, code, verb) (increase(apiserver_request_total{code=~"4..",job="apiserver",verb=~"LIST|GET|POST|PUT|PATCH|DELETE"}[1h]))
        - record: code_verb:apiserver_request_total:increase1h
          expr: sum by (cluster, code, verb) (increase(apiserver_request_total{code=~"5..",job="apiserver",verb=~"LIST|GET|POST|PUT|PATCH|DELETE"}[1h]))
