# k8s-monitoring v3.x configuration
cluster:
  name: management-cluster

# Destinations configuration for v3.x (replaces externalServices)
destinations:
  - name: "prometheus"
    type: "prometheus"
    url: "{{ index .Values.global.secrets \"mimir_host\" }}/api/v1/push"
    auth:
      tenantId: "{{ index .Values.global.secrets \"mimir_tenant_id\" }}"
      basicAuth:
        username: "{{ index .Values.global.secrets \"mimir_username\" }}"
        password: "{{ index .Values.global.secrets \"mimir_password\" }}"
    secret:
      create: false
      name: grafana-agent-credentials
      namespace: "grafana-agent"
  - name: "loki"
    type: "loki"
    url: "{{ index .Values.global.secrets \"loki_host\" }}/loki/api/v1/push"
    auth:
      tenantId: "{{ index .Values.global.secrets \"loki_tenant_id\" }}"
      basicAuth:
        username: "{{ index .Values.global.secrets \"loki_username\" }}"
        password: "{{ index .Values.global.secrets \"loki_password\" }}"
    secret:
      create: false
      name: grafana-agent-credentials
      namespace: "grafana-agent"

# Feature enablement - opt-in for v3.x
clusterMetrics:
  enabled: true

podLogs:
  enabled: true

# Cluster Events
clusterEvents:
  enabled: true

# Node exporter
nodeExporter:
  enabled: true

# Kube-state-metrics
kubeStateMetrics:
  enabled: true

# Control plane components
controlPlane:
  enabled: true
  components:
    kubeApiserver:
      enabled: true
    kubeControllerManager:
      enabled: true
    kubeScheduler:
      enabled: true
    kubeProxy:
      enabled: true
    kubelet:
      enabled: true

# CRDs management
crds:
  create: false

# Disable components not needed
opencost:
  enabled: false

# Alloy metrics instance configuration
alloy-metrics:
  enabled: true
  alloy:
    resources:
      requests:
        cpu: 100m
        memory: 128Mi
      limits:
        cpu: 500m
        memory: 512Mi

# Global configuration for secrets
global:
  secrets:
    mimir_host: ""
    mimir_tenant_id: ""
    mimir_username: ""
    mimir_password: ""
    loki_host: ""
    loki_tenant_id: ""
    loki_username: ""
    loki_password: ""