# k8s-monitoring v3.x compatible configuration
cluster:
  name: management-cluster

# External services configuration for v3.x
externalServices:
  prometheus:
    host: "{{ index .Values.global.secrets \"mimir_host\" }}"
    queryEndpoint: /prometheus/api/v1/query
    writeEndpoint: /api/v1/push
    tenantId: "{{ index .Values.global.secrets \"mimir_tenant_id\" }}"
    basicAuth:
      username: "{{ index .Values.global.secrets \"mimir_username\" }}"
      password: "{{ index .Values.global.secrets \"mimir_password\" }}"
    secret:
      create: false
      name: grafana-agent-credentials
      namespace: "grafana-agent"
  loki:
    host: "{{ index .Values.global.secrets \"loki_host\" }}"
    writeEndpoint: /loki/api/v1/push
    tenantId: "{{ index .Values.global.secrets \"loki_tenant_id\" }}"
    basicAuth:
      username: "{{ index .Values.global.secrets \"loki_username\" }}"
      password: "{{ index .Values.global.secrets \"loki_password\" }}"
    secret:
      create: false
      name: grafana-agent-credentials
      namespace: "grafana-agent"

# Feature enablement
logs:
  enabled: true
traces:
  enabled: false

# Metrics collection configuration for v3.x
metrics:
  enabled: true
  
  # Kubernetes component metrics
  kubernetesMonitoring:
    enabled: true
    
  # Node exporter
  nodeExporter:
    enabled: true
    
  # Kube-state-metrics
  kubeStateMetrics:
    enabled: true
    
  # cAdvisor
  cadvisor:
    enabled: true
    
  # Control plane components
  controlPlane:
    enabled: true
    components:
      kubeApiserver:
        enabled: true
      kubeControllerManager:
        enabled: true
      kubeScheduler:
        enabled: true
      kubeProxy:
        enabled: true
      kubelet:
        enabled: true

# CRDs management
crds:
  create: false

# Disable components not needed
opencost:
  enabled: false

alloy:
  alloy:
    resources:
      requests:
        cpu: 100m
        memory: 128Mi
      limits:
        cpu: 500m
        memory: 512Mi

# Global configuration for secrets
global:
  secrets:
    mimir_host: ""
    mimir_tenant_id: ""
    mimir_username: ""
    mimir_password: ""
    loki_host: ""
    loki_tenant_id: ""
    loki_username: ""
    loki_password: ""