apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- api-ingress.yaml
- ca-cert.yaml
- cert-issuer.yaml
- ClusterSecretStore.yaml
- console-ingress.yaml
- env-configurations-ExternalSecret.yaml
- minio-console-creds.yaml
# - minio-operator-ExternalSecret.yaml
- push-secret-console.yaml
- push-secret.yaml
- random-password-generator.yaml
- tenant-cert.yaml
- tenant.yaml