apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: ca-cert
  namespace: minio-operator
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name:  minio-qumulus-secrets-store
  target:
    name: operator-ca-tls-minio-qumulus  # name of the k8s Secret to be created
  data:
  - secretKey: ca.crt
    remoteRef:
      key: minio-qumulus-ca-tls
      property: ca.crt