apiVersion: external-secrets.io/v1alpha1
kind: PushSecret
metadata:
  name: minio-console-creds
  annotations:
    argocd.argoproj.io/sync-wave: "2"
    annotations:
      argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  updatePolicy: Replace
  deletionPolicy: Delete
  refreshInterval: 5s
  secretStoreRefs:
    - name: vault-secrets
      kind: ClusterSecretStore
  selector:
    secret:
      name: qumulus-user-0
  data:
    - match:
        secretKey: CONSOLE_SECRET_KEY
        remoteRef:
          remoteKey: minio/console
          property: password
      metadata:
        secretPushFormat: string
    - match:
        secretKey: CONSOLE_ACCESS_KEY
        remoteRef:
          remoteKey: minio/console
          property: username
      metadata:
        secretPushFormat: string