apiVersion: external-secrets.io/v1alpha1
kind: PushSecret
metadata:
  name: minio-creds
  annotations:
    argocd.argoproj.io/sync-wave: "2"
    annotations:
      argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  updatePolicy: Replace
  deletionPolicy: Delete
  refreshInterval: 5s
  secretStoreRefs:
    - name: vault-secrets
      kind: ClusterSecretStore
  selector:
    secret:
      name: qumulus-env-configuration
  data:
    - match:
        secretKey: minioPassword
        remoteRef:
          remoteKey: minio/password
          property: minio-password
      metadata:
        secretPushFormat: string
    - match:
        secretKey: minioUser
        remoteRef:
          remoteKey: minio/username
          property: minio-username
      metadata:
        secretPushFormat: string