apiVersion: generators.external-secrets.io/v1alpha1
kind: Password
metadata:
  name: minio-random-password
  annotations:
    argocd.argoproj.io/hook: PreSync
    annotations:
      argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  length: 32
  digits: 10
  symbols: 6
  noUpper: false
  allowRepeat: false
