# Simple ESO configuration for LiveKit credentials
---
apiVersion: generators.external-secrets.io/v1alpha1
kind: Password
metadata:
  name: livekit-api-key-gen
  namespace: livekit
  annotations:
    argocd.argoproj.io/sync-wave: "-3"
spec:
  length: 16
  digits: 5
  symbols: 0
  noUpper: false
  allowRepeat: true
---
apiVersion: generators.external-secrets.io/v1alpha1
kind: Password
metadata:
  name: livekit-api-secret-gen
  namespace: livekit
  annotations:
    argocd.argoproj.io/sync-wave: "-3"
spec:
  length: 40
  digits: 10
  symbols: 0
  noUpper: false
  allowRepeat: true
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: livekit-keys-file
  namespace: livekit
  annotations:
    argocd.argoproj.io/sync-wave: "-2"
spec:
  refreshInterval: "0"
  target:
    name: livekit-keys-file
    template:
      type: Opaque
      data:
        keys.yaml: |
          {{ printf "LKAPI%s" .apiKey }}: {{ .apiSecret }}
  dataFrom:
  - sourceRef:
      generatorRef:
        apiVersion: generators.external-secrets.io/v1alpha1
        kind: Password
        name: livekit-api-key-gen
    rewrite:
    - regexp:
        source: "password"
        target: "apiKey"
  - sourceRef:
      generatorRef:
        apiVersion: generators.external-secrets.io/v1alpha1
        kind: Password
        name: livekit-api-secret-gen
    rewrite:
    - regexp:
        source: "password"
        target: "apiSecret"