apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Helm charts
helmCharts:
# LiveKit server
- name: livekit-server
  repo: https://helm.livekit.io
  version: 1.9.0
  releaseName: livekit-server
  namespace: livekit
  valuesFile: values.yaml

# Redis Cluster for LiveKit
- name: redis-cluster
  repo: https://charts.bitnami.com/bitnami
  version: 11.0.7
  releaseName: redis-cluster
  namespace: livekit
  valuesFile: redis-values.yaml

# Additional custom resources
resources:
# Core LiveKit resources
- turn-service.yaml
# - turn-tls-certificate.yaml  # Disabled - using UDP TURN only
- ws-ingress.yaml
# External Secrets configuration
- external-secrets.yaml
- minio-credentials.yaml
- turn-credentials.yaml
- clustersecretstore.yaml
# Performance and optimization
- priority-classes.yaml
- performance-config.yaml
- connection-optimizer.yaml
# Jobs
- node-tuning-job.yaml

# Patches to modify Helm-generated resources
patches:
- path: deployment-volumes-patch.yaml
  target:
    kind: Deployment
    name: livekit-server
- path: configmap-patch.yaml
  target:
    kind: ConfigMap
    name: livekit-server
- path: service-patch.yaml
  target:
    kind: Service
    name: livekit-server
- path: deployment-turn-patch.yaml
  target:
    kind: Deployment
    name: livekit-server
- path: deployment-config-patch.yaml
  target:
    kind: Deployment
    name: livekit-server