# External Secret to create MinIO credentials for LiveKit
---
apiVersion: generators.external-secrets.io/v1alpha1
kind: Password
metadata:
  name: livekit-minio-password
  namespace: livekit
  annotations:
    argocd.argoproj.io/sync-wave: "-2"
spec:
  length: 32
  digits: 10
  symbols: 5
  symbolCharacters: "-_"
  noUpper: false
  allowRepeat: true
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: livekit-minio-credentials
  namespace: livekit
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  refreshInterval: "0"  # Only sync once
  target:
    name: livekit-minio-credentials
    template:
      type: Opaque
      data:
        MINIO_ACCESS_KEY: "minio"
        MINIO_SECRET_KEY: "{{ .password }}"
  dataFrom:
    - sourceRef:
        generatorRef:
          apiVersion: generators.external-secrets.io/v1alpha1
          kind: Password
          name: livekit-minio-password