---
apiVersion: scheduling.k8s.io/v1
kind: PriorityClass
metadata:
  name: livekit-critical-priority
value: 1000
globalDefault: false
description: "Critical priority class for LiveKit server core workloads"
---
apiVersion: scheduling.k8s.io/v1
kind: PriorityClass
metadata:
  name: livekit-high-priority
value: 500
globalDefault: false
description: "High priority class for LiveKit server and egress workloads"
---
apiVersion: scheduling.k8s.io/v1
kind: PriorityClass
metadata:
  name: livekit-medium-priority
value: 200
globalDefault: false
description: "Medium priority class for LiveKit ingress workloads"
---
apiVersion: scheduling.k8s.io/v1
kind: PriorityClass
metadata:
  name: livekit-low-priority
value: 100
globalDefault: false
description: "Low priority class for LiveKit monitoring workloads"