apiVersion: grafana.integreatly.org/v1beta1
kind: GrafanaDatasource
metadata:
  name: mimir-alertmanager
spec:
  valuesFrom:
  - targetPath: "url"
    valueFrom:
      secretKeyRef:
        name: "grafana-datasource-credentials"
        key: "mimir_host"
  - targetPath: "basicAuthUser"
    valueFrom:
      secretKeyRef:
        name: "grafana-datasource-credentials"
        key: "mimir_username"
  - targetPath: "secureJsonData.basicAuthPassword"
    valueFrom:
      secretKeyRef:
        name: "grafana-datasource-credentials"
        key: "mimir_password"
  instanceSelector:
    matchLabels:
      cluster_type: management
  datasource:
    name: Alertmanager
    type: alertmanager
    access: proxy
    url: ${mimir_host}
    basicAuth: true
    basicAuthUser: ${mimir_username}
    isDefault: true
    jsonData:
      httpHeaderName1: X-Scope-OrgID
      tlsSkipVerify: true
      implementation: mimir
      handleGrafanaManagedAlerts: true
    secureJsonData:
      basicAuthPassword : ${mimir_password}
      httpHeaderValue1: {{ .Values.tenant }}
