
apiVersion: grafana.integreatly.org/v1beta1
kind: Grafana
metadata:
  name: grafana
  labels:
    cluster_type: management
spec:
  config:
    log:
      mode: "console"
    auth:
      disable_login_form: "false"
  deployment:
    spec:
      template:
        spec:
          containers:
            - name: grafana
              image: grafana/grafana:10.3.1
  ingress:
    metadata:
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt
    spec:
      ingressClassName: nginx
      rules:
        - host: grafana.{{ .Values.domain }}
          http:
            paths:
              - backend:
                  service:
                    name: grafana-service
                    port:
                      number: 3000
                path: /
                pathType: Prefix
      tls:
        - hosts:
            - grafana.{{ .Values.domain }}
          secretName: grafana
