apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: grafana
spec:
  issuerRef:
    group: cert-manager.io
    kind: ClusterIssuer
    name: letsencrypt
  dnsNames:
    - grafana.{{ .Values.domain }}
  secretName: grafana
