resources:
  limits: {}
  requests:
    memory: 256Mi
    cpu: 250m
replicaCount: 3
architecture: high-availability
extraEnvVars:
  - name: MEMCACHED_MAX_CONNECTIONS
    value: "1024"
  - name: MEMCACHED_CACHE_SIZE
    value: "1024"
  - name: MEMCACHED_MAX_ITEM_SIZE
    value: "5242880"
