# External Secret for MinIO password generation
---
apiVersion: generators.external-secrets.io/v1alpha1
kind: Password
metadata:
  name: minio-password
  namespace: minio-tenant
spec:
  length: 32
  digits: 10
  symbols: 5
  symbolCharacters: "-_"
  noUpper: false
  allowRepeat: true
---
apiVersion: generators.external-secrets.io/v1alpha1
kind: Password
metadata:
  name: minio-console-password
  namespace: minio-tenant
spec:
  length: 32
  digits: 10
  symbols: 5
  symbolCharacters: "-_"
  noUpper: false
  allowRepeat: true
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: minio-credentials
  namespace: minio-tenant
spec:
  refreshInterval: "0" # Only generate once
  target:
    name: tenant-env-configuration
    template:
      type: Opaque
      data:
        config.env: |
          export MINIO_BROWSER="on"
          export MINIO_ROOT_USER="minio"
          export MINIO_ROOT_PASSWORD="{{ `{{ .password }}` }}"
        minioUser: "minio"
        minioPassword: "{{ `{{ .password }}` }}"
  dataFrom:
  - sourceRef:
      generatorRef:
        apiVersion: generators.external-secrets.io/v1alpha1
        kind: Password
        name: minio-password
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: minio-console-user
  namespace: minio-tenant
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  refreshInterval: "0" # Only generate once
  target:
    name: tenant-user-0
    template:
      type: Opaque
      data:
        CONSOLE_ACCESS_KEY: "console"
        CONSOLE_SECRET_KEY: "{{ `{{ .password }}` }}"
  dataFrom:
  - sourceRef:
      generatorRef:
        apiVersion: generators.external-secrets.io/v1alpha1
        kind: Password
        name: minio-console-password
