apiVersion: generators.external-secrets.io/v1alpha1
kind: Password
metadata:
  name: minio-random-password
  namespace: {{ .Values.tenant.namespace }}
spec:
  length: 32
  digits: 10
  symbols: 6
  noUpper: false
  allowRepeat: false
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: minio-console-creds
  namespace: {{ .Values.tenant.namespace }}
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
    argocd.argoproj.io/sync-wave: "-1"
spec:
  dataFrom:
  - sourceRef:
      generatorRef:
        apiVersion: generators.external-secrets.io/v1alpha1
        kind: Password
        name: minio-random-password
  refreshInterval: "0"
  target:
    name: {{ .Values.tenant.name }}-user-0
    creationPolicy: Owner
    deletionPolicy: Retain
    template:
      data:
        CONSOLE_ACCESS_KEY: console
        CONSOLE_SECRET_KEY: "{{ `{{ .password }}` }}"
      engineVersion: v2
      mergePolicy: Replace
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: minio-root-creds
  namespace: {{ .Values.tenant.namespace }}
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
    argocd.argoproj.io/sync-wave: "-1"
spec:
  dataFrom:
  - sourceRef:
      generatorRef:
        apiVersion: generators.external-secrets.io/v1alpha1
        kind: Password
        name: minio-random-password
  refreshInterval: 8750h
  target:
    name: {{ .Values.tenant.name }}-env-configuration
    creationPolicy: Owner
    deletionPolicy: Retain
    template:
      data:
        config.env: |
          export MINIO_BROWSER="on"
          export MINIO_ROOT_USER="minio"
          export MINIO_ROOT_PASSWORD="{{ `{{ .password }}` }}"
        minioPassword: "{{ `{{ .password }}` }}"
        minioUser: minio
      engineVersion: v2
      mergePolicy: Replace