apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ .Values.tenant.name }}-api-metrics
  namespace: {{ .Values.tenant.namespace }}
  labels:
    app: minio
    component: api-metrics
spec:
  selector:
    matchLabels:
      v1.min.io/tenant: {{ .Values.tenant.name }}
      v1.min.io/service-type: "minio"
  endpoints:
  - port: minio-api
    interval: 30s
    path: /minio/v2/metrics/cluster
    scrapeTimeout: 10s
  namespaceSelector:
    matchNames:
    - {{ .Values.tenant.namespace }}
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ .Values.tenant.name }}-console-metrics
  namespace: {{ .Values.tenant.namespace }}
  labels:
    app: minio
    component: console-metrics
spec:
  selector:
    matchLabels:
      v1.min.io/tenant: {{ .Values.tenant.name }}
      v1.min.io/service-type: "console"
  endpoints:
  - port: console-api
    interval: 30s
    path: /api/v1/prometheus
    scrapeTimeout: 10s
  namespaceSelector:
    matchNames:
    - {{ .Values.tenant.namespace }}