apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: general-rules
  labels:
    app: grafana-agent
    tenant: {{ .Values.tenant }}
spec:
  groups:
    - name: general.rules
      rules:
        - alert: TargetDown
          expr: 100 * (count by (cluster, job, namespace, service) (up == 0) / count by (cluster, job, namespace, service) (up)) > 10
          for: 10m
          labels:
            severity: critical
          annotations:
            description: '{{`{{`}} printf "%.4g" $value }}% of the {{`{{`}} $labels.job {{`}}`}} targets in {{`{{`}} $labels.instance {{`}}`}} are down.'
            runbook_url: https://runbooks.prometheus-operator.dev/runbooks/general/targetdown
            summary: One or more targets are unreachable.
        # - alert: InfoInhibitor
        #   expr: ALERTS{severity="info"} == 1 unless on (namespace, cluster) ALERTS{alertname!="InfoInhibitor",alertstate="firing",severity=~"warning|critical"} == 1
        #   labels:
        #     severity: none
        #   annotations:
        #     description: |
        #         This is an alert that is used to inhibit info alerts.
        #         By themselves, the info-level alerts are sometimes very noisy, but they are relevant when combined with
        #         other alerts.
        #         This alert fires whenever there's a severity="info" alert, and stops firing when another alert with a
        #         severity of 'warning' or 'critical' starts firing on the same namespace.
        #         This alert should be routed to a null receiver and configured to inhibit alerts with severity="info".
        #     runbook_url: https://runbooks.prometheus-operator.dev/runbooks/general/infoinhibitor
        #     summary: Info-level alert inhibition.
