apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: kubernetes-system-alerts
  labels:
    app: grafana-agent
    tenant: {{ .Values.tenant }}
spec:
  groups:
    - name: kubernetes-system
      rules:
        - alert: KubeVersionMismatch
          expr: count by (cluster) (count by (git_version, cluster) (label_replace(kubernetes_build_info{job!~"kube-dns|coredns"}, "git_version", "$1", "git_version", "(v[0-9]*.[0-9]*).*"))) > 1
          for: 15m
          labels:
            severity: warning
          annotations:
            description: There are {{`{{`}} $value {{`}}`}} different semantic versions of Kubernetes components running.
            runbook_url: https://runbooks.prometheus-operator.dev/runbooks/kubernetes/kubeversionmismatch
            summary: Different semantic versions of Kubernetes components running.
        - alert: KubeClientErrors
          expr: |-
            (sum by (cluster, instance, job, namespace) (rate(rest_client_requests_total{code=~"5..",job="apiserver"}[5m])) / sum by (cluster, instance, job, namespace) (rate(rest_client_requests_total{job="apiserver"}[5m]))) > 0.01
          for: 15m
          labels:
            severity: warning
          annotations:
            description: Kubernetes API server client '{{`{{`}} $labels.job {{`}}`}}/{{`{{`}} $labels.instance {{`}}`}}' is experiencing {{`{{`}} $value | humanizePercentage {{`}}`}} errors.'
            runbook_url: https://runbooks.prometheus-operator.dev/runbooks/kubernetes/kubeclienterrors
            summary: Kubernetes API server client is experiencing errors.
