# apiVersion: monitoring.coreos.com/v1
# kind: PrometheusRule
# metadata:
#   name: kubernetes-system-controller-manager-alerts
#   labels:
#     app: grafana-agent
#     tenant: {{ .Values.tenant }}
# spec:
#   groups:
#     - name: kubernetes-system-controller-manager
#       rules:
#         - alert: KubeControllerManagerDown
#           expr: absent(up{job="kube-controller-manager"} == 1)
#           for: 15m
#           labels:
#             severity: critical
#           annotations:
#             description: KubeControllerManager has disappeared from Prometheus target discovery.
#             runbook_url: https://runbooks.prometheus-operator.dev/runbooks/kubernetes/kubecontrollermanagerdown
#             summary: Target disappeared from Prometheus target discovery.
