# apiVersion: monitoring.coreos.com/v1
# kind: PrometheusRule
# metadata:
#   name: kubernetes-system-scheduler-alerts
#   labels:
#     app: grafana-agent
#     tenant: {{ .Values.tenant }}
# spec:
#   groups:
#     - name: kubernetes-system-scheduler
#       rules:
#         - alert: KubeSchedulerDown
#           expr: absent(up{job="kube-scheduler"} == 1)
#           for: 15m
#           labels:
#             severity: critical
#           annotations:
#             description: KubeScheduler has disappeared from Prometheus target discovery.
#             runbook_url: https://runbooks.prometheus-operator.dev/runbooks/kubernetes/kubeschedulerdown
#             summary: Target disappeared from Prometheus target discovery.
