apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: kubernetes-system-kubelet-alerts
  labels:
    app: grafana-agent
    tenant: {{ .Values.tenant }}
spec:
  groups:
    - name: kubernetes-system-kubelet
      rules:
        - alert: KubeNodeNotReady
          expr: kube_node_status_condition{condition="Ready",job="integrations/kubernetes/kube-state-metrics",status="true"} == 0
          for: 15m
          labels:
            severity: warning
          annotations:
            description: '{{`{{`}} $labels.node {{`}}`}} has been unready for more than 15 minutes.'
            runbook_url: https://runbooks.prometheus-operator.dev/runbooks/kubernetes/kubenodenotready
            summary: Node is not ready.
        - alert: KubeNodeUnreachable
          expr: (kube_node_spec_taint{effect="NoSchedule",job="integrations/kubernetes/kube-state-metrics",key="node.kubernetes.io/unreachable"} unless ignoring (key, value) kube_node_spec_taint{job="integrations/kubernetes/kube-state-metrics",key=~"ToBeDeletedByClusterAutoscaler|cloud.google.com/impending-node-termination|aws-node-termination-handler/spot-itn"}) == 1
          for: 15m
          labels:
            severity: warning
          annotations:
            description: '{{`{{`}} $labels.node {{`}}`}} is unreachable and some workloads may be rescheduled.'
            runbook_url: https://runbooks.prometheus-operator.dev/runbooks/kubernetes/kubenodeunreachable
            summary: Node is unreachable.
        - alert: KubeletTooManyPods
          expr: |-
            count by (cluster, node) ((kube_pod_status_phase{job="integrations/kubernetes/kube-state-metrics",phase="Running"} == 1) * on (instance, pod, namespace, cluster) group_left (node) topk by (instance, pod, namespace, cluster) (1, kube_pod_info{job="integrations/kubernetes/kube-state-metrics"})) / max by (cluster, node) (kube_node_status_capacity{job="integrations/kubernetes/kube-state-metrics",resource="pods"} != 1) > 0.95
          for: 15m
          labels:
            severity: info
          annotations:
            description: Kubelet '{{`{{`}} $labels.node {{`}}`}}' is running at {{`{{`}} $value | humanizePercentage {{`}}`}} of its Pod capacity.
            runbook_url: https://runbooks.prometheus-operator.dev/runbooks/kubernetes/kubelettoomanypods
            summary: Kubelet is running at capacity.
        - alert: KubeNodeReadinessFlapping
          expr: sum by (cluster, node) (changes(kube_node_status_condition{condition="Ready",job="integrations/kubernetes/kube-state-metrics",status="true"}[15m])) > 2
          for: 15m
          labels:
            severity: warning
          annotations:
            description: The readiness status of node {{`{{`}} $labels.node {{`}}`}} has changed {{`{{`}} $value {{`}}`}} times in the last 15 minutes.
            runbook_url: https://runbooks.prometheus-operator.dev/runbooks/kubernetes/kubenodereadinessflapping
            summary: Node readiness status is flapping.
        - alert: KubeletPlegDurationHigh
          expr: node_quantile:kubelet_pleg_relist_duration_seconds:histogram_quantile{quantile="0.99"} >= 10
          for: 5m
          labels:
            severity: warning
          annotations:
            description: The Kubelet Pod Lifecycle Event Generator has a 99th percentile duration of {{`{{`}} $value {{`}}`}} seconds on node {{`{{`}} $labels.node {{`}}`}}.
            runbook_url: https://runbooks.prometheus-operator.dev/runbooks/kubernetes/kubeletplegdurationhigh
            summary: Kubelet Pod Lifecycle Event Generator is taking too long to relist.
        - alert: KubeletPodStartUpLatencyHigh
          expr: histogram_quantile(0.99, sum by (cluster, instance, le) (rate(kubelet_pod_worker_duration_seconds_bucket{job="integrations/kubernetes/kubelet"}[5m]))) * on (cluster, instance) group_left (node) kubelet_node_name{job="integrations/kubernetes/kubelet"} > 60
          for: 15m
          labels:
            severity: warning
          annotations:
            description: Kubelet Pod startup 99th percentile latency is {{`{{`}} $value {{`}}`}} seconds on node {{`{{`}} $labels.node {{`}}`}}.
            runbook_url: https://runbooks.prometheus-operator.dev/runbooks/kubernetes/kubeletpodstartuplatencyhigh
            summary: Kubelet Pod startup latency is too high.
        - alert: KubeletClientCertificateExpiration
          expr: kubelet_certificate_manager_client_ttl_seconds < 604800
          labels:
            severity: warning
          annotations:
            description: Client certificate for Kubelet on node {{`{{`}} $labels.node {{`}}`}} expires in {{`{{`}} $value | humanizeDuration {{`}}`}}.
            runbook_url: https://runbooks.prometheus-operator.dev/runbooks/kubernetes/kubeletclientcertificateexpiration
            summary: Kubelet client certificate is about to expire.
        - alert: KubeletClientCertificateExpiration
          expr: kubelet_certificate_manager_client_ttl_seconds < 86400
          labels:
            severity: critical
          annotations:
            description: Client certificate for Kubelet on node {{`{{`}} $labels.node {{`}}`}} expires in {{`{{`}} $value | humanizeDuration {{`}}`}}.
            runbook_url: https://runbooks.prometheus-operator.dev/runbooks/kubernetes/kubeletclientcertificateexpiration
            summary: Kubelet client certificate is about to expire.
        - alert: KubeletServerCertificateExpiration
          expr: kubelet_certificate_manager_server_ttl_seconds < 604800
          labels:
            severity: warning
          annotations:
            description: Server certificate for Kubelet on node {{`{{`}} $labels.node {{`}}`}} expires in {{`{{`}} $value | humanizeDuration {{`}}`}}.
            runbook_url: https://runbooks.prometheus-operator.dev/runbooks/kubernetes/kubeletservercertificateexpiration
            summary: Kubelet server certificate is about to expire.
        - alert: KubeletServerCertificateExpiration
          expr: kubelet_certificate_manager_server_ttl_seconds < 86400
          labels:
            severity: critical
          annotations:
            description: Server certificate for Kubelet on node {{`{{`}} $labels.node {{`}}`}} expires in {{`{{`}} $value | humanizeDuration {{`}}`}}.
            runbook_url: https://runbooks.prometheus-operator.dev/runbooks/kubernetes/kubeletservercertificateexpiration
            summary: Kubelet server certificate is about to expire.
        - alert: KubeletClientCertificateRenewalErrors
          expr: increase(kubelet_certificate_manager_client_expiration_renew_errors[5m]) > 0
          for: 15m
          labels:
            severity: warning
          annotations:
            description: Kubelet on node {{`{{`}} $labels.node {{`}}`}} has failed to renew its client certificate ({{`{{`}} $value | humanize {{`}}`}} errors in the last 5 minutes).
            runbook_url: https://runbooks.prometheus-operator.dev/runbooks/kubernetes/kubeletclientcertificaterenewalerrors
            summary: Kubelet has failed to renew its client certificate.
        - alert: KubeletServerCertificateRenewalErrors
          expr: increase(kubelet_server_expiration_renew_errors[5m]) > 0
          for: 15m
          labels:
            severity: warning
          annotations:
            description: Kubelet on node {{`{{`}} $labels.node {{`}}`}} has failed to renew its server certificate ({{`{{`}} $value | humanize {{`}}`}} errors in the last 5 minutes).
            runbook_url: https://runbooks.prometheus-operator.dev/runbooks/kubernetes/kubeletservercertificaterenewalerrors
            summary: Kubelet has failed to renew its server certificate.
        - alert: KubeletDown
          expr: absent(up{job="integrations/kubernetes/kubelet"} == 1)
          for: 15m
          labels:
            severity: critical
          annotations:
            description: Kubelet has disappeared from Prometheus target discovery.
            runbook_url: https://runbooks.prometheus-operator.dev/runbooks/kubernetes/kubeletdown
            summary: Target disappeared from Prometheus target discovery.
