apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: kubernetes
  namespace: {{ .Release.Namespace }}
spec:
  provider:
    kubernetes:
      remoteNamespace: {{ .Release.Namespace }}
      server:
        url: "https://kubernetes.default.svc.cluster.local:443"
        caProvider:
          type: ConfigMap
          name: kube-root-ca.crt
          key: ca.crt
      auth:
        serviceAccount:
          name: harbor-external-secrets
          namespace: {{ .Release.Namespace }}