{{ $harborURL := .Values.harborURL | default "repo.livekit-demo.cloudportal.app" }}
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: harbor-docker-registry
  namespace: {{ .Release.Namespace }}
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  refreshInterval: "1h"
  secretStoreRef:
    name: kubernetes
    kind: SecretStore
  target:
    name: harbor-docker-registry
    template:
      type: kubernetes.io/dockerconfigjson
      engineVersion: v2
      data:
        .dockerconfigjson: |
          {{`{{ $password := .password -}}`}}
          {{`{{ $auth := printf "admin:%s" $password | b64enc -}}`}}
          {{`{{ printf "{\"auths\":{\"`}}{{ $harborURL }}{{`\":{\"username\":\"admin\",\"password\":\"%s\",\"auth\":\"%s\"}}}" $password $auth }}`}}
  data:
  - secretKey: password
    remoteRef:
      key: harbor-auth
      property: password