apiVersion: v1
kind: ServiceAccount
metadata:
  name: harbor-external-secrets
  namespace: {{ .Release.Namespace }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: harbor-external-secrets
rules:
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: harbor-external-secrets
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: harbor-external-secrets
subjects:
- kind: ServiceAccount
  name: harbor-external-secrets
  namespace: {{ .Release.Namespace }}
---
apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: harbor-registry-secrets
spec:
  provider:
    kubernetes:
      remoteNamespace: {{ .Release.Namespace }}
      server:
        url: "https://kubernetes.default.svc.cluster.local:443"
        caProvider:
          type: ConfigMap
          name: kube-root-ca.crt
          namespace: default
          key: ca.crt
      auth:
        serviceAccount:
          name: harbor-external-secrets
          namespace: {{ .Release.Namespace }}