# Password generators for Harbor internal secrets
---
# Core secret generator (16 chars)
apiVersion: generators.external-secrets.io/v1alpha1
kind: Password
metadata:
  name: harbor-core-secret-gen
  namespace: {{ .Release.Namespace }}
spec:
  length: 16
  digits: 4
  symbols: 0
  noUpper: false
  allowRepeat: false
---
# XSRF key generator (32 chars)
apiVersion: generators.external-secrets.io/v1alpha1
kind: Password
metadata:
  name: harbor-xsrf-key-gen
  namespace: {{ .Release.Namespace }}
spec:
  length: 32
  digits: 8
  symbols: 0
  noUpper: false
  allowRepeat: false
---
# Registry HTTP secret generator (16 chars)
apiVersion: generators.external-secrets.io/v1alpha1
kind: Password
metadata:
  name: harbor-registry-secret-gen
  namespace: {{ .Release.Namespace }}
spec:
  length: 16
  digits: 4
  symbols: 0
  noUpper: false
  allowRepeat: false
---
# ExternalSecret for harbor-core-secret
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: harbor-core-eso-secret
  namespace: {{ .Release.Namespace }}
spec:
  refreshInterval: "0"
  target:
    name: harbor-core-eso-secret
    template:
      data:
        secret: "{{ `{{ .coreSecret }}` }}"
        CSRF_KEY: "{{ `{{ .xsrfKey }}` }}"
  dataFrom:
  - sourceRef:
      generatorRef:
        apiVersion: generators.external-secrets.io/v1alpha1
        kind: Password
        name: harbor-core-secret-gen
    rewrite:
    - regexp:
        source: "password"
        target: "coreSecret"
  - sourceRef:
      generatorRef:
        apiVersion: generators.external-secrets.io/v1alpha1
        kind: Password
        name: harbor-xsrf-key-gen
    rewrite:
    - regexp:
        source: "password"
        target: "xsrfKey"
---
# ExternalSecret for harbor-jobservice-secret
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: harbor-jobservice-eso-secret
  namespace: {{ .Release.Namespace }}
spec:
  refreshInterval: "0"
  secretStoreRef:
    name: kubernetes
    kind: SecretStore
  target:
    name: harbor-jobservice-eso-secret
  data:
  # Use the same core secret value
  - secretKey: JOBSERVICE_SECRET
    remoteRef:
      key: harbor-core-eso-secret
      property: secret
---
# ExternalSecret for registry secret
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: harbor-registry-eso-secret
  namespace: {{ .Release.Namespace }}
spec:
  refreshInterval: "0"
  target:
    name: harbor-registry-eso-secret
  dataFrom:
  - sourceRef:
      generatorRef:
        apiVersion: generators.external-secrets.io/v1alpha1
        kind: Password
        name: harbor-registry-secret-gen
    rewrite:
    - regexp:
        source: "password"
        target: "REGISTRY_HTTP_SECRET"
