apiVersion: generators.external-secrets.io/v1alpha1
kind: Password
metadata:
  name: harbor-password
  annotations:
    argocd.argoproj.io/sync-wave: "-2"
spec:
  length: 24
  digits: 8
  symbols: 0
  noUpper: false
  allowRepeat: false
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: harbor-auth
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  refreshInterval: "0"
  target:
    name: harbor-auth
  dataFrom:
  - sourceRef:
      generatorRef:
        apiVersion: generators.external-secrets.io/v1alpha1
        kind: Password
        name: harbor-password