apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: harbor-core-metrics
  namespace: {{ .Release.Namespace }}
  labels:
    app: harbor
    component: core-metrics
spec:
  selector:
    matchLabels:
      app: harbor
      component: core
  endpoints:
  - port: http
    interval: 30s
    path: /api/v2.0/metrics
    scrapeTimeout: 10s
  namespaceSelector:
    matchNames:
    - {{ .Release.Namespace }}
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: harbor-registry-metrics
  namespace: {{ .Release.Namespace }}
  labels:
    app: harbor
    component: registry-metrics
spec:
  selector:
    matchLabels:
      app: harbor
      component: registry
  endpoints:
  - port: metrics
    interval: 30s
    path: /metrics
    scrapeTimeout: 10s
  namespaceSelector:
    matchNames:
    - {{ .Release.Namespace }}
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: harbor-jobservice-metrics
  namespace: {{ .Release.Namespace }}
  labels:
    app: harbor
    component: jobservice-metrics
spec:
  selector:
    matchLabels:
      app: harbor
      component: jobservice
  endpoints:
  - port: metrics
    interval: 30s
    path: /metrics
    scrapeTimeout: 10s
  namespaceSelector:
    matchNames:
    - {{ .Release.Namespace }}