apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "trivoh.fullname" . }}
  labels:
    {{- include "trivoh.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "trivoh.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "trivoh.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
      - name: {{ .Chart.Name }}
        image: "repo.{{ .Values.domain }}/livekit-demo/newtrivoh:{{ .Values.image.tag | default .Chart.AppVersion }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
        - name: http
          containerPort: {{ .Values.service.targetPort }}
          protocol: TCP
        livenessProbe:
          httpGet:
            path: /
            port: http
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /
            port: http
          initialDelaySeconds: 5
          periodSeconds: 5
        resources:
          {{- toYaml .Values.resources | nindent 10 }}
        env:
          - name: LIVEKIT_URL
            value: "wss://livekit.{{ .Values.domain }}"
          - name: LIVEKIT_API_URL
            value: "https://api.{{ .Values.domain }}"
          - name: TRIVOH_API_URL
            value: "https://api.{{ .Values.domain }}"
          {{- with .Values.env }}
          {{- range . }}
          {{- if and (ne .name "LIVEKIT_URL") (ne .name "LIVEKIT_API_URL") (ne .name "TRIVOH_API_URL") }}
          - name: {{ .name }}
            {{- if .value }}
            value: {{ .value | quote }}
            {{- else if .valueFrom }}
            valueFrom:
              {{- toYaml .valueFrom | nindent 14 }}
            {{- end }}
          {{- end }}
          {{- end }}
          {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
